phrase:
  access_token: 0aa6faba72864e5d1248216c0bb81c9746e698535ce6e78b5c0c852614e0310b
  project_id: 6ba5bb5fe5a45d5fbc3e03bb95965ce3
  file_format: simple_json
  
  push:
    sources:
    - file: ./<locale_name>.json
      params:
        locale_id: de
  pull:
    targets:
    - file: ./<locale_name>.json
