phrase:
    project_id: 733f238d9489893454760270d0389549

    push:
        sources:
            - file: ./<locale_name>.json
            params:
                file_format: simple_json
                locale_id: en
    pull:
        targets:
            - file: ./<locale_name>.json
            params:
                file_format: simple_json
