phrase:
  access_token: e66a7cc1a43fc899c3d34911346bace7d82bd5544b541b9d8601d9a65e8785b5
  project_id: 48b698e887efa6e115f14e3dc02f8cef
  file_format: simple_json
  
  push:
    sources:
    - file: ./<locale_name>.json
      params:
        locale_id: en
  pull:
    targets:
    - file: ./<locale_name>.json
